In [1]:
from nd2reader import ND2Reader
import numpy as np
video_path = './example_blank.nd2'
nd2_frames = ND2Reader(video_path)

In [2]:
num_frames = len(nd2_frames)
print(f'num_frames: {num_frames}')
# frames are access like a numpy array so
# nd2_frames[frame_num] will return the frame

time_steps = nd2_frames.get_timesteps()
start_time = time_steps[0]
end_time = time_steps[-1]
duration = float(end_time - start_time)/1000.0
print(f'duration: {duration}')

avg_frame_rate = float(num_frames)/duration
print(f'avg_frame_rate: {avg_frame_rate}')

# print(time_steps/1000.0)

# when converting from an ND2 to an mp4 or avi etc, 
# we can set a time base as: 
# time_base = (1.0/1000.0)*(1/avg_frame_rate)
# where the 1/1000 puts it into milliseconds
# or we can just by default choose 1/25000 since that appears to be fairly common

print(nd2_frames[0])

num_frames: 200
duration: 2.23373388671875
avg_frame_rate: 89.53618028949303
[[807 767 661 ... 652 655 616]
 [740 836 843 ... 539 573 595]
 [686 724 727 ... 666 518 567]
 ...
 [ 97 105  98 ... 112 120 106]
 [ 87 106 108 ... 107 107  91]
 [106 101 108 ... 124 112 118]]
