In [32]:
import av
import numpy as np
video_path = './phase_contrast.mp4'
video_container = av.open(video_path)

In [33]:
video_stream = video_container.streams.video[0]
num_video_frames = video_stream.frames
print(f'num_video_frames: {num_video_frames}')
print()

average_frame_rate = float(video_stream.average_rate)
print(f'average_frame_rate: {average_frame_rate}')

guessed_frame_rate = video_stream.guessed_rate
print(f'guessed_frame_rate: {guessed_frame_rate}')

base_frame_rate = video_stream.base_rate
print(f'base_frame_rate: {base_frame_rate}')

video_stream_timebase = video_stream.time_base
print(f'video_stream_timebase: {video_stream_timebase}')
# NOTE: we WILL NEED this timebase to set any non ND2 output videos time base

video_stream_start_time = float(video_stream.start_time * video_stream_timebase)
print(f'video_stream_start_time: {video_stream_start_time}')

video_duration = float(video_stream.duration * video_stream_timebase) - video_stream_start_time
print(f'video_duration: {video_duration}')

computed_frame_rate = float(num_video_frames)/video_duration
print(f'computed_frame_rate: {computed_frame_rate}')

# to implement a proper set reset for our videos, we will need to capture the pts of the frame
# and then seek to wherever we need to go, and then seek back to that pts we captured

video_frames = video_container.decode()
video_container.seek(0)
frame = next(video_frames)
# TODO: have to figure out a way to determine if the video is yuv, rbg or just gray
#       i think it's frame.format.name
# https://github.com/PyAV-Org/PyAV/blob/9ac05d9ac902d71ecb2fe80f04dcae454008378c/av/video/frame.pyx#L187
# print(f'format: {frame.format.name}')
# print(f'is rgb? {frame.format.is_rgb}')
# print(f'bits per pixel: {frame.format.bits_per_pixel}')

print('ndarray')
print(frame.to_ndarray())  # original format can be 3 channel etc
print(frame.to_ndarray(format='gray'))  # grayscale format only converts if necessary so can always call it
# frame_times = []  # only adding time stamps to a list because printing a list all at once is easier to see than one per line
# for frame_num in range(num_video_frames):
#     frame = next(video_frames)
#     # these two methods of getting the time stamp in seconds are equivalent
#     # so we can use the frame.pts to write the output video
#     # frame_time_stamp = float(frame.pts * video_stream_timebase) - video_stream_start_time
#     frame_time_stamp = frame.time - video_stream_start_time
#     frame_times.append(frame_time_stamp)
#     # do stuff with the frame i.e. match etc
# print(frame_times)

num_video_frames: 428

average_frame_rate: 43.1333344083074
guessed_frame_rate: 25
base_frame_rate: 25
video_stream_timebase: 1/25000
video_stream_start_time: 0.01124
video_duration: 9.911439999999999
computed_frame_rate: 43.18242354289589
ndarray
[[ 31  30  28 ...  37  37  34]
 [ 30  31  28 ...  38  39  38]
 [ 29  32  29 ...  42  36  41]
 ...
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]]
[[17 16 14 ... 24 24 21]
 [16 17 14 ... 26 27 26]
 [15 19 15 ... 30 23 29]
 ...
 [ 3  3  3 ...  3  3  3]
 [ 3  3  3 ...  3  3  3]
 [ 3  3  3 ...  3  3  3]]


In [40]:
# video_container.close()
video_container.seek(0)
frame = next(video_frames)
print('ndarray')
print(frame.to_ndarray())  # original format can be 3 channel etc
print(frame.to_ndarray(format='gray'))  # grayscale format only converts if necessary so can always call it

ndarray
[[ 31  30  28 ...  37  37  34]
 [ 30  31  28 ...  38  39  38]
 [ 29  32  29 ...  42  36  41]
 ...
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]]
[[17 16 14 ... 24 24 21]
 [16 17 14 ... 26 27 26]
 [15 19 15 ... 30 23 29]
 ...
 [ 3  3  3 ...  3  3  3]
 [ 3  3  3 ...  3  3  3]
 [ 3  3  3 ...  3  3  3]]


In [41]:
video_stream.codec_context.width

2304

In [42]:
video_stream.codec_context.height

1152

In [44]:
np_frame = frame.to_ndarray(format='gray')
np_frame.shape

(1152, 2304)