In [1]:
import nd2
import numpy as np
video_dir = './videos_to_track/video_suite/'

video_file = '2021-10-11_calcium_experiment_A002.nd2'
# video_file = '0000-00-00_example_blank_A000.nd2'
# video_file = '0000-00-00_example_A000.nd2'

video_path = video_dir + video_file
nd2_file = nd2.ND2File(video_path)

In [2]:
nd2_frames = nd2_file.to_xarray(delayed=True)
print(f'is legacy: {nd2_file.is_legacy}')
print(len(nd2_frames))
# nd2_file.experiment[0]

is legacy: False
1001


In [3]:
print(nd2_file.attributes)
# nd2_file.attributes.bitsPerComponentInMemory


Attributes(bitsPerComponentInMemory=16, bitsPerComponentSignificant=16, componentCount=1, heightPx=252, pixelDataType='unsigned', sequenceCount=1001, widthBytes=2260, widthPx=1129, compressionLevel=None, compressionType=None, tileHeightPx=None, tileWidthPx=None, channelCount=1)


In [4]:
frame = nd2_frames[1000].to_numpy()
print(frame)

[[1224 1291 1314 ... 1662 1499 1621]
 [1263 1316 1372 ... 1492 1547 1470]
 [1195 1168 1351 ... 1542 1572 1464]
 ...
 [1331 1088 1308 ... 1700 1468 1540]
 [1175 1365 1238 ... 1594 1541 1596]
 [1297 1246 1362 ... 1494 1479 1571]]


In [5]:
def timeSteps(self_nd2_file):
    time_steps = []
    for i in range(self_nd2_file._rdr._seq_count()):
        coords = self_nd2_file._rdr._coords_from_seq_index(i)
        _chs = self_nd2_file._rdr._frame_metadata(i).get('channels')
        stamp = _chs[0]['time']['relativeTimeMs']
        time_steps.append(stamp/1000.0)
        # print(coords, stamp)
    return time_steps

In [6]:
time_steps = timeSteps(nd2_file)

In [7]:
print(f'num time steps: {len(time_steps)}')
print(f'{time_steps}')

num time steps: 1001
[-0.021833004474639893, -0.011825924396514892, -0.0018178677558898925, 0.008189944744110108, 0.018198001384735107, 0.02820605802536011, 0.03821411466598511, 0.04822217130661011, 0.058229983806610104, 0.0682370638847351, 0.0782451205253601, 0.0882531771659851, 0.09826098966598511, 0.1082690463066101, 0.1182771029472351, 0.1282851595878601, 0.1382929720878601, 0.1483010287284851, 0.15830810880661011, 0.1683161654472351, 0.17832397794723512, 0.1883320345878601, 0.19834009122848512, 0.2083481478691101, 0.21835596036911012, 0.2283640170097351, 0.2383710970878601, 0.2483791537284851, 0.2583869662284851, 0.2683950228691101, 0.2784030795097351, 0.2884111361503601, 0.2984189486503601, 0.3084270052909851, 0.3184350619316101, 0.3284421420097351, 0.3384499545097351, 0.3484580111503601, 0.3584660677909851, 0.3684741244316101, 0.3784819369316101, 0.3884899935722351, 0.3984980502128601, 0.4085051302909851, 0.4185129427909851, 0.4285209994316101, 0.43852905607223513, 0.44853711271

In [8]:
def timeStamp(self_nd2_file, frame_num):
    _chs = self_nd2_file._rdr._frame_metadata(frame_num).get('channels')
    time_stamp = _chs[0]['time']['relativeTimeMs']
    return time_stamp

def getTimeStamps(self_nd2_file):
    time_stamps = []
    max_frame_num = self_nd2_file._rdr._seq_count() # is this different to the num of frames from the xarray? probably not but worth checking?
    for frame_num in range(max_frame_num):
        time_stamps.append(timeStamp(self_nd2_file, frame_num)/1000.0)
    return time_stamps

In [9]:
print(getTimeStamps(nd2_file))

[-0.021833004474639893, -0.011825924396514892, -0.0018178677558898925, 0.008189944744110108, 0.018198001384735107, 0.02820605802536011, 0.03821411466598511, 0.04822217130661011, 0.058229983806610104, 0.0682370638847351, 0.0782451205253601, 0.0882531771659851, 0.09826098966598511, 0.1082690463066101, 0.1182771029472351, 0.1282851595878601, 0.1382929720878601, 0.1483010287284851, 0.15830810880661011, 0.1683161654472351, 0.17832397794723512, 0.1883320345878601, 0.19834009122848512, 0.2083481478691101, 0.21835596036911012, 0.2283640170097351, 0.2383710970878601, 0.2483791537284851, 0.2583869662284851, 0.2683950228691101, 0.2784030795097351, 0.2884111361503601, 0.2984189486503601, 0.3084270052909851, 0.3184350619316101, 0.3284421420097351, 0.3384499545097351, 0.3484580111503601, 0.3584660677909851, 0.3684741244316101, 0.3784819369316101, 0.3884899935722351, 0.3984980502128601, 0.4085051302909851, 0.4185129427909851, 0.4285209994316101, 0.43852905607223513, 0.4485371127128601, 0.458545169353